// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd_jkNzi9tzraEvuFkS_EGkDkFbZcG5p0',
    appId: '1:270175615151:android:0c30d3adf6e7d27ffcfc5a',
    messagingSenderId: '270175615151',
    projectId: 'news-reminder-app',
    storageBucket: 'news-reminder-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZGRwBftUjp23xSYX1nSAS3XLgyqAcy8I',
    appId: '1:270175615151:ios:2209742010abe9a4fcfc5a',
    messagingSenderId: '270175615151',
    projectId: 'news-reminder-app',
    storageBucket: 'news-reminder-app.appspot.com',
    androidClientId: '270175615151-i64c9vmi902s30tgmhh317lgvnd7fmeg.apps.googleusercontent.com',
    iosClientId: '270175615151-eh7m8ko2tv9dnc8so9fupfr0bmlrfb1v.apps.googleusercontent.com',
    iosBundleId: 'com.trading.newsReminderApp',
  );
}
